version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: "github-actions"
    directory: "/examples/"
    schedule:
      interval: monthly
